[project]
name = "repl-nix-voxbotgpt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.10",
    "gtts>=2.5.4",
    "pydub>=0.25.1",
    "pytelegrambotapi>=4.25.0",
    "speechrecognition>=3.11.0",
]
